#!/bin/bash

function listProjects()
{
	echo "Available projects: "
	echo "- all (sync all projects at once)"
	for PROJECT in *; do
		if [ -d $PROJECT ] && [ -f "$PROJECT/tools/autosync.php" ]; then
			echo "- ${PROJECT}"
		fi
	done
}

function setTitle()
{
	echo -n -e "\033]0;$1\007"
}

function checkSetup()
{
	PERSON=`whoami`
	PROJ=`echo $1 | tr '[:upper:]' '[:lower:]'`
	ADDITION=""
	if [ -d "${HOME}/Development/${1}/website" ]; then
		# if Project has website dir than it's a website so add .dev.magneds.com
		# if not than it's a library
		ADDITION=".dev.magneds.com"
	fi
	/usr/bin/ssh dev.magneds.com bash <<ENDSSH
	if [ ! -d /sites/$PERSON.$PROJ$ADDITION ]; then
		echo "creating /sites/${PERSON}.${PROJ}$ADDITION"
		mkdir -p /sites/$PERSON.$PROJ$ADDITION
	fi
ENDSSH
}

PHP=`which php`
cd ~/Development
clear

if [ "${1}" = "" ]; then
	listProjects
elif [ "${1}" = "all" ]; then
	for PROJECT in ~/Development/*/tools/autosync.php; do
		PARENT=`dirname $PROJECT`
		GPARENT=`dirname $PARENT`
		checkSetup `basename $GPARENT`
		osascript -e 'tell application "Terminal" to activate' -e 'tell application "System Events" to tell process "Terminal" to keystroke "t" using command down' && osascript -e "tell application \"Terminal\" to do script \"cd $(dirname $PROJECT) && php autosync.php\" in selected tab of the front window";
	done
	osascript -e 'tell application "System Events" to click (first button of (front window of (application process "Terminal")) whose role description is "minimize button")';
else
	if [ -f "${1}/tools/autosync.php" ]; then
		cd "${1}/tools"
		setTitle $1
		checkSetup $1
		$PHP autosync.php
	else
		echo -e "PROJECT '${1}' NOT FOUND"
		listProjects
	fi
fi